# Generated by Django 5.2 on 2025-05-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_aboutcomment_blog_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcomment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='aboutrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='aboutrating',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.blogpost'),
        ),
    ]
